name = "tracewayapp"
main = "./functions/worker.ts"
compatibility_date = "2025-02-01"

[assets]
directory = "./out"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
